{% set name = "MaAsLin3" %}
{% set version = "0.99.16" %}
{% set sha256 = "a25f594882d3caf1c5f66c9f0d925b80d7609d0346f9dc03f6e19575de7362d8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/biobakery/{{ name|lower }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  run_exports: '{{ pin_subpackage("maaslin3", max_pin="x.x") }}'
  noarch: generic

# Suggests: knitr, testthat (>= 2.1.0), rmarkdown, markdown, kableExtra
requirements:

  host:
    - biocgenerics >=0.54.0,<0.55.0
    - summarizedexperiment >=1.38.0,<1.39.0
    - treesummarizedexperiment >=2.16.0,<2.17.0
    - r-base
    - r-dplyr
    - r-ggnewscale
    - r-ggplot2
    - r-lme4
    - r-lmertest
    - r-logging
    - r-multcomp
    - r-optparse
    - r-patchwork
    - r-pbapply
    - r-plyr
    - r-rcolorbrewer
    - r-rlang
    - r-scales
    - r-survival
    - r-tibble

  run:
    - biocgenerics >=0.54.0,<0.55.0
    - summarizedexperiment >=1.38.0,<1.39.0
    - treesummarizedexperiment >=2.16.0,<2.17.0
    - r-base
    - r-dplyr
    - r-ggnewscale
    - r-ggplot2
    - r-lme4
    - r-lmertest
    - r-logging
    - r-multcomp
    - r-optparse
    - r-patchwork
    - r-pbapply
    - r-plyr
    - r-rcolorbrewer
    - r-rlang
    - r-scales
    - r-survival
    - r-tibble

test:
  commands:
    - $R -e "library('{{ name|lower }}')"

about:
  home: https://github.com/biobakery/{{ name|lower }}
  license: Custom
  summary: '"Refining and extending generalized multivariate linear models for meta-omic association discovery"'
  description: MaAsLin 3 refines and extends generalized multivariate linear models for meta-omicron association discovery. It finds abundance and prevalence associations between microbiome meta-omics features and complex metadata in population-scale epidemiological studies. The software includes multiple analysis methods (including support for multiple covariates, repeated measures, and ordered predictors), filtering, normalization, and transform options to customize analysis for your specific study.
  license_file: LICENSE

